# Generated by Django 6.0.1 on 2026-01-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('harassment', 'Harassment'), ('abuse', 'Abuse'), ('scam', 'Scam or Money Request'), ('inappropriate', 'Inappropriate Behavior'), ('other', 'Other')], max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
