# Generated by Django 6.0.1 on 2026-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('call', 'Call Notification')], default='text', max_length=10),
        ),
    ]
