# Generated by Django 6.0.1 on 2026-02-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_publicmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.publicmessage'),
        ),
    ]
