# Generated by Django 6.0.1 on 2026-01-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='swiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('swiper', 'target')},
        ),
    ]
