# Generated by Django 6.0.1 on 2026-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_district_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
