# Generated by Django 6.0.1 on 2026-01-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_swipe_limit',
            field=models.IntegerField(default=5),
        ),
    ]
