# Generated by Django 6.0.1 on 2026-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_daily_swipe_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_swipe_limit',
            field=models.IntegerField(default=8),
        ),
    ]
