# Generated by Django 6.0.1 on 2026-02-06 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_daily_swipe_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='back_swipes_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_back_swipe_limit',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='user',
            name='last_back_swipe_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 2, 6)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='normal', max_length=10),
        ),
    ]
