name: Flutter Build Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # A good open-jdk distro for Android builds
          java-version: '17'
          cache: 'gradle'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: |
          cd mobile
          flutter pub get
          
      - name: Build APK
        run: |
          cd mobile
          flutter build apk --release
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: twingle-android-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
